### ISSUE TITLE
cps rate may be affected by render time with many points on "Show Evolution" plot

### ISSUE THREAD

**Issue by jbeale1** [OpenGammaProject/Gamma-MCA#209]
With a large number of accumulated points, for example ~ 1 million on my low-end PC, it takes a long time to render the time series plot. The displayed "cps" number may be relative to active plotting time and not wall-clock time, so the first reported value for cps immediately after closing the time series graph to return to the spectrum graph may be very large, for example 10x or more larger than the typical value. 
Subsequent display of the time series plot shows this spuriously large number as a real data point, while it may be an artifact of available CPU time and not a deviation in true count rate. This could be some unavoidable consequence of the code being a browser plugin (?)  The two high outlier data points visible in the plot below were caused by this effect.  It does not occur in a plot if the "Show Evolution" button is never used.
![GammMCA-LargePeaks-2024-01-09_16-08-45](https://github.com/OpenGammaProject/Gamma-MCA/assets/7452231/ba23989d-54ea-45f5-b4fb-6c0decb8e982)

**Comment by jbeale1** [comment]
I see there was another report of the cps timing off in the opposite direction, so maybe this is again a synchronization issue with the other side via the serial-over-USB data stream. https://github.com/OpenGammaProject/Gamma-MCA/issues/19

**Comment by NuclearPhoenixx** [comment]
Yeah this sounds like a synchronization error because the plot refresh takes so long. Looks like it skipped a refresh without new data resulting in cps=0 just before loading new data together with the data it missed resulting in the spike. Plotly unfortunately gets very slow very quickly when there are a lot of data points. I would love to enable hardware acceleration via WebGL for this which significantly boosts performance, but there is a critical feature that's currently broken (see https://github.com/plotly/plotly.js/issues/5365).

In the mean time, I think I'll just add a feature to automatically decrease the time resolution to limit the number of points in this plot. I think that'd be the easiest fix until we get HW accel. :+1:

**Comment by NuclearPhoenixx** [comment]
Let me know if https://github.com/OpenGammaProject/Gamma-MCA/pull/210 fixed that for you. I introduced downsampling so that should limit the number of points to 10k to limit the performance hit. Be sure to reload the app to apply the update, if it's still too slow then I'll reopen.

**Comment by jbeale1** [comment]
Yes, the new version of 2024-01-10 does have much faster plotting when there are a large number of points accumulated. There is no longer a large glitch in the reported cps rate when closing the evolution graph. There are still smaller, down-then-up glitches upon opening the graph each time, and after reaching ~ 1.2M points, so long as the time graph stays open, the reported cps rate drops off significantly (it should be nearly constant around 800 cps everywhere to the right of X=300 on this graph). Maybe recalculating a live time plot during data collection is not compatible with lower-power systems like my fitlet2 Linux Mint miniPC (Intel J3455 @ 1.50GHz).

![GammaEvoGraph_2024-01-10_08-40-55](https://github.com/OpenGammaProject/Gamma-MCA/assets/7452231/8c61e5b9-d38c-4b35-8e11-f886272b7de8)

**Comment by NuclearPhoenixx** [comment]
Huh, I don't understand. It actually looks worse now 😕 

Can you please do the exact same test as above so that we have a direct comparison?

It's possible that your system is too weak. Like I said the number of points displayed on the plot is limited to 10k now, so you're not actually seeing any of it because you're only at like 2k and you already have problems. I'm guessing that you run into issues earlier now since the count rate is so much higher. It's certainly not helping that all the code runs in a single thread at the moment... Maybe I can find a way to optimize this by using background threads.

**Comment by NuclearPhoenixx** [comment]
I'll add background threads on my todo list and see what I can do to boost performance. Other than that, I'm afraid there is not much I can do. I'll wait to see what you keep reporting.

**Comment by jbeale1** [comment]
Yes, it may be too much to ask for consistent timing accuracy on a slower miniPC like mine, while also doing live GUI plots. I am testing now at just my normal background rate of 16 cps (having moved the board trimpot threshold up a bit, to eliminate a very narrow spike at the lowest energy end of the spectrum that I presume is noise). It will take some hours to reach enough plot points to be relevant to the question.

**Comment by NuclearPhoenixx** [comment]
I made one last update today and removed the markers from the time evolution chart. Refresh time was only like 1/5 the time before, so it's a huge improvement and it actually looks better too.

As it stands now it looks like >95% of the total time taken to refresh the plot on screen is caused by Plotly alone. So AFAIK there is literally nothing I can do except for downsampling without them implementing WebGL correctly (hardware acceleration) or using something like OffscreenCanvas to offload tasks to background threads.

After ~40 minutes it already took ~200ms to update the plot once on my PC, which is *a long time* (again, 95% - 98% of that goes exclusively to the Plotly update function). So in fact, I'm surprised your machine is handling it *this* well 😆

**Comment by jbeale1** [comment]
Just to confirm your own notes, after running a background accumulation at 11 cps avg. for 14 hours on a laptop with Intel i5-7300U CPU @ 2.60GHz, I see no trace of the spikes or droop effects in the time plot due to display of the graph, that I saw with the slower system.  
![image](https://github.com/OpenGammaProject/Gamma-MCA/assets/7452231/0e0374b1-0ca1-4d94-8362-014280f8fc78)
